[package]
name = "zero-gln-auth"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
pumpkin-plugin-api = "0.1.0-dev+26.2-26.45"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_json = "1.0"
argon2 = { version = "0.5", features = ["std"] }
waki = "0.5"
